deployment:
  tasks:
    - export DEPLOYPATH=/home/mytempoesp/site.mytempo.esp.br/public_html
    - /bin/cp -R *.html $DEPLOYPATH
    - /bin/cp -R System $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH
